name: Чтобы не забыть
title: Чтобы не забыть
description: Записная книжка рассеянного [в пространстве и времени] программиста
theme: jekyll-theme-cayman
permalink: /:categories/:title/
timezone: Europe/Moscow
excerpt_separator: <!--more-->
lang: ru-RU
plugins:
  - jekyll-sass-converter
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
paginate_path: "/posts/page/:num"
paginate: 5
sass:
  sass_dir: _sass
  style: compressed
months:
  - Январь
  - Февраль
  - Март
  - Апрель
  - Май
  - Июнь
  - Июль
  - Август
  - Сентярь
  - Октябрь
  - Ноябрь
  - Декабрь