name: Чтобы не забыть
title: Чтобы не забыть
description: Записная книжка рассеянного [в пространстве и времени] программиста
theme: jekyll-theme-cayman
permalink: /:categories/:title/
timezone: Europe/Moscow
paginate: 5
paginate_path: "/posts/page:num/"
excerpt_separator: <!--more-->
plugins:
  - jekyll-paginate-v2
pagination:
  enabled: true
  permalink: '/posts/page:num/'
  sort_reverse: true
  title: ':title - Посты. Страница :num'
gems:
  - jekyll-paginate-v2
