name: Чтобы не забыть
title: Чтобы не забыть
description: Записная книжка рассеянного [в пространстве и времени] программиста
theme: jekyll-theme-cayman
permalink: /:categories/:title/
timezone: Europe/Moscow
excerpt_separator: <!--more-->
lang: ru-RU
plugins:
  - jekyll-paginate
  - jekyll-sass-converter
paginate_path: "/posts/page/:num"
paginate: 5
sass:
    sass_dir: _sass
    style: compressed