# -*- mode: ruby -*-

dir = File.dirname(File.expand_path(__FILE__))

require 'yaml'
require "#{dir}/puphpet/ruby/deep_merge.rb"
require "#{dir}/puphpet/ruby/to_bool.rb"
require "#{dir}/puphpet/ruby/puppet.rb"

configValues = YAML.load_file("#{dir}/puphpet/config.yaml")

yiiEnv = ENV['YII_ENV'] ? ENV['YII_ENV'] : 'dev'
yiiDebug = ENV['YII_DEBUG'] ? ENV['YII_DEBUG'] : true
provider = ENV['VAGRANT_DEFAULT_PROVIDER'] ? ENV['VAGRANT_DEFAULT_PROVIDER'] : 'local'
if File.file?("#{dir}/puphpet/config-#{provider}.yaml")
  custom = YAML.load_file("#{dir}/puphpet/config-#{provider}.yaml")
  configValues.deep_merge!(custom)
end

if File.file?("#{dir}/puphpet/config-custom.yaml")
  custom = YAML.load_file("#{dir}/puphpet/config-custom.yaml")
  configValues.deep_merge!(custom)
end

data = configValues['vagrantfile']

Vagrant.require_version '>= 1.8.1'

Vagrant.configure('2') do |config|
  config.hostmanager.enabled = true
  config.hostmanager.ip_resolver = proc do |vm, resolving_vm|
    # in virtualbox 0 is nat network
    vm.provider.driver.read_guest_ip(1)
  end
  config.vm.provision 'shell' do |s|
    s.path = "#{dir}/puphpet/bootstrap.sh"
    s.env = { YII_ENV: yiiEnv, YII_DEBUG: yiiDebug }
  end
  eval File.read("#{dir}/puphpet/vagrant/Vagrantfile-#{data['target']}")
end
